//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Code\you\Qik\Code\Current\QikAntlr\QikTemplate.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CygSoft.Qik.Antlr {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class QikTemplateLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, CONST=12, STRING=13, IDENTIFIER=14, VARIABLE=15, FLOAT=16, 
		INT=17, WS=18, COMMENT=19, LINE_COMMENT=20;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "CONST", "STRING", "IDENTIFIER", "VARIABLE", "FLOAT", 
		"INT", "LETTER", "DIGIT", "WS", "COMMENT", "LINE_COMMENT"
	};


	public QikTemplateLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public QikTemplateLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'=>'", "';'", "'=='", "'!='", "'+'", "'?'", "':'", "'()'", "'('", 
		"','", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"CONST", "STRING", "IDENTIFIER", "VARIABLE", "FLOAT", "INT", "WS", "COMMENT", 
		"LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "QikTemplate.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static QikTemplateLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x16', '\xB0', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x5', '\r', 'Y', '\n', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\a', '\xE', '_', '\n', '\xE', 
		'\f', '\xE', '\xE', '\xE', '\x62', '\v', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\a', '\xF', 'i', '\n', '\xF', 
		'\f', '\xF', '\xE', '\xF', 'l', '\v', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\a', '\x10', 'r', '\n', '\x10', '\f', '\x10', 
		'\xE', '\x10', 'u', '\v', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\a', '\x11', 'z', '\n', '\x11', '\f', '\x11', '\xE', '\x11', 
		'}', '\v', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', '\x11', '\x81', 
		'\n', '\x11', '\x3', '\x12', '\x6', '\x12', '\x84', '\n', '\x12', '\r', 
		'\x12', '\xE', '\x12', '\x85', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x15', '\x6', '\x15', '\x8D', '\n', '\x15', '\r', 
		'\x15', '\xE', '\x15', '\x8E', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\a', '\x16', '\x97', '\n', 
		'\x16', '\f', '\x16', '\xE', '\x16', '\x9A', '\v', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\a', '\x17', '\xA5', '\n', 
		'\x17', '\f', '\x17', '\xE', '\x17', '\xA8', '\v', '\x17', '\x3', '\x17', 
		'\x5', '\x17', '\xAB', '\n', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x98', '\x2', '\x18', '\x3', '\x3', '\x5', 
		'\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', 
		'\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', 
		'\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', 
		'%', '\x2', '\'', '\x2', ')', '\x14', '+', '\x15', '-', '\x16', '\x3', 
		'\x2', '\a', '\x3', '\x2', '$', '$', '\x6', '\x2', '\x43', '\\', '\x61', 
		'\x61', '\x63', '|', '\x101', '\x101', '\x3', '\x2', '\x32', ';', '\x5', 
		'\x2', '\v', '\f', '\xE', '\xF', '\"', '\"', '\x4', '\x2', '\f', '\f', 
		'\xF', '\xF', '\x2', '\xBC', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', 
		'\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x3', '/', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\a', '\x34', '\x3', '\x2', '\x2', '\x2', '\t', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '\v', ':', '\x3', '\x2', '\x2', '\x2', '\r', '<', '\x3', 
		'\x2', '\x2', '\x2', '\xF', '>', '\x3', '\x2', '\x2', '\x2', '\x11', '@', 
		'\x3', '\x2', '\x2', '\x2', '\x13', '\x43', '\x3', '\x2', '\x2', '\x2', 
		'\x15', '\x45', '\x3', '\x2', '\x2', '\x2', '\x17', 'G', '\x3', '\x2', 
		'\x2', '\x2', '\x19', 'X', '\x3', '\x2', '\x2', '\x2', '\x1B', 'Z', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '\x65', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'm', '\x3', '\x2', '\x2', '\x2', '!', '\x80', '\x3', '\x2', '\x2', '\x2', 
		'#', '\x83', '\x3', '\x2', '\x2', '\x2', '%', '\x87', '\x3', '\x2', '\x2', 
		'\x2', '\'', '\x89', '\x3', '\x2', '\x2', '\x2', ')', '\x8C', '\x3', '\x2', 
		'\x2', '\x2', '+', '\x92', '\x3', '\x2', '\x2', '\x2', '-', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '/', '\x30', '\a', '?', '\x2', '\x2', '\x30', '\x31', 
		'\a', '@', '\x2', '\x2', '\x31', '\x4', '\x3', '\x2', '\x2', '\x2', '\x32', 
		'\x33', '\a', '=', '\x2', '\x2', '\x33', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'\x34', '\x35', '\a', '?', '\x2', '\x2', '\x35', '\x36', '\a', '?', '\x2', 
		'\x2', '\x36', '\b', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\a', 
		'#', '\x2', '\x2', '\x38', '\x39', '\a', '?', '\x2', '\x2', '\x39', '\n', 
		'\x3', '\x2', '\x2', '\x2', ':', ';', '\a', '-', '\x2', '\x2', ';', '\f', 
		'\x3', '\x2', '\x2', '\x2', '<', '=', '\a', '\x41', '\x2', '\x2', '=', 
		'\xE', '\x3', '\x2', '\x2', '\x2', '>', '?', '\a', '<', '\x2', '\x2', 
		'?', '\x10', '\x3', '\x2', '\x2', '\x2', '@', '\x41', '\a', '*', '\x2', 
		'\x2', '\x41', '\x42', '\a', '+', '\x2', '\x2', '\x42', '\x12', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\x44', '\a', '*', '\x2', '\x2', '\x44', 
		'\x14', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', '.', '\x2', 
		'\x2', '\x46', '\x16', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\a', '+', 
		'\x2', '\x2', 'H', '\x18', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\a', 
		'V', '\x2', '\x2', 'J', 'K', '\a', '\x43', '\x2', '\x2', 'K', 'Y', '\a', 
		'\x44', '\x2', '\x2', 'L', 'M', '\a', 'U', '\x2', '\x2', 'M', 'N', '\a', 
		'R', '\x2', '\x2', 'N', 'O', '\a', '\x43', '\x2', '\x2', 'O', 'P', '\a', 
		'\x45', '\x2', '\x2', 'P', 'Y', '\a', 'G', '\x2', '\x2', 'Q', 'R', '\a', 
		'P', '\x2', '\x2', 'R', 'S', '\a', 'G', '\x2', '\x2', 'S', 'T', '\a', 
		'Y', '\x2', '\x2', 'T', 'U', '\a', 'N', '\x2', '\x2', 'U', 'V', '\a', 
		'K', '\x2', '\x2', 'V', 'W', '\a', 'P', '\x2', '\x2', 'W', 'Y', '\a', 
		'G', '\x2', '\x2', 'X', 'I', '\x3', '\x2', '\x2', '\x2', 'X', 'L', '\x3', 
		'\x2', '\x2', '\x2', 'X', 'Q', '\x3', '\x2', '\x2', '\x2', 'Y', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', 'Z', '`', '\a', '$', '\x2', '\x2', '[', '\\', 
		'\a', '$', '\x2', '\x2', '\\', '_', '\a', '$', '\x2', '\x2', ']', '_', 
		'\n', '\x2', '\x2', '\x2', '^', '[', '\x3', '\x2', '\x2', '\x2', '^', 
		']', '\x3', '\x2', '\x2', '\x2', '_', '\x62', '\x3', '\x2', '\x2', '\x2', 
		'`', '^', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x61', '\x63', '\x3', '\x2', '\x2', '\x2', '\x62', '`', '\x3', 
		'\x2', '\x2', '\x2', '\x63', '\x64', '\a', '$', '\x2', '\x2', '\x64', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x65', 'j', '\x5', '%', '\x13', '\x2', 
		'\x66', 'i', '\x5', '%', '\x13', '\x2', 'g', 'i', '\x5', '\'', '\x14', 
		'\x2', 'h', '\x66', '\x3', '\x2', '\x2', '\x2', 'h', 'g', '\x3', '\x2', 
		'\x2', '\x2', 'i', 'l', '\x3', '\x2', '\x2', '\x2', 'j', 'h', '\x3', '\x2', 
		'\x2', '\x2', 'j', 'k', '\x3', '\x2', '\x2', '\x2', 'k', '\x1E', '\x3', 
		'\x2', '\x2', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\a', 
		'\x42', '\x2', '\x2', 'n', 's', '\x5', '%', '\x13', '\x2', 'o', 'r', '\x5', 
		'%', '\x13', '\x2', 'p', 'r', '\x5', '\'', '\x14', '\x2', 'q', 'o', '\x3', 
		'\x2', '\x2', '\x2', 'q', 'p', '\x3', '\x2', '\x2', '\x2', 'r', 'u', '\x3', 
		'\x2', '\x2', '\x2', 's', 'q', '\x3', '\x2', '\x2', '\x2', 's', 't', '\x3', 
		'\x2', '\x2', '\x2', 't', ' ', '\x3', '\x2', '\x2', '\x2', 'u', 's', '\x3', 
		'\x2', '\x2', '\x2', 'v', 'w', '\x5', '#', '\x12', '\x2', 'w', '{', '\a', 
		'\x30', '\x2', '\x2', 'x', 'z', '\x5', '\'', '\x14', '\x2', 'y', 'x', 
		'\x3', '\x2', '\x2', '\x2', 'z', '}', '\x3', '\x2', '\x2', '\x2', '{', 
		'y', '\x3', '\x2', '\x2', '\x2', '{', '|', '\x3', '\x2', '\x2', '\x2', 
		'|', '\x81', '\x3', '\x2', '\x2', '\x2', '}', '{', '\x3', '\x2', '\x2', 
		'\x2', '~', '\x7F', '\a', '\x30', '\x2', '\x2', '\x7F', '\x81', '\x5', 
		'#', '\x12', '\x2', '\x80', 'v', '\x3', '\x2', '\x2', '\x2', '\x80', '~', 
		'\x3', '\x2', '\x2', '\x2', '\x81', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\x82', '\x84', '\x5', '\'', '\x14', '\x2', '\x83', '\x82', '\x3', '\x2', 
		'\x2', '\x2', '\x84', '\x85', '\x3', '\x2', '\x2', '\x2', '\x85', '\x83', 
		'\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\x3', '\x2', '\x2', '\x2', 
		'\x86', '$', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\t', '\x3', 
		'\x2', '\x2', '\x88', '&', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', 
		'\t', '\x4', '\x2', '\x2', '\x8A', '(', '\x3', '\x2', '\x2', '\x2', '\x8B', 
		'\x8D', '\t', '\x5', '\x2', '\x2', '\x8C', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8D', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x8E', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x90', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\b', '\x15', '\x2', 
		'\x2', '\x91', '*', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\a', 
		'\x31', '\x2', '\x2', '\x93', '\x94', '\a', ',', '\x2', '\x2', '\x94', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '\x95', '\x97', '\v', '\x2', '\x2', 
		'\x2', '\x96', '\x95', '\x3', '\x2', '\x2', '\x2', '\x97', '\x9A', '\x3', 
		'\x2', '\x2', '\x2', '\x98', '\x99', '\x3', '\x2', '\x2', '\x2', '\x98', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9B', '\x3', '\x2', '\x2', 
		'\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\a', 
		',', '\x2', '\x2', '\x9C', '\x9D', '\a', '\x31', '\x2', '\x2', '\x9D', 
		'\x9E', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\b', '\x16', '\x2', 
		'\x2', '\x9F', ',', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\a', 
		'\x31', '\x2', '\x2', '\xA1', '\xA2', '\a', '\x31', '\x2', '\x2', '\xA2', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA5', '\n', '\x6', '\x2', 
		'\x2', '\xA4', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA8', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xAA', '\x3', '\x2', '\x2', 
		'\x2', '\xA8', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAB', '\a', 
		'\xF', '\x2', '\x2', '\xAA', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xAD', '\a', '\f', '\x2', '\x2', '\xAD', '\xAE', '\x3', 
		'\x2', '\x2', '\x2', '\xAE', '\xAF', '\b', '\x17', '\x2', '\x2', '\xAF', 
		'.', '\x3', '\x2', '\x2', '\x2', '\x11', '\x2', 'X', '^', '`', 'h', 'j', 
		'q', 's', '{', '\x80', '\x85', '\x8E', '\x98', '\xA6', '\xAA', '\x3', 
		'\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace CygSoft.Qik.Antlr
