//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Code\you\Qik\Code\Current\QikAntlr\QikTemplate.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CygSoft.Qik.Antlr {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class QikTemplateLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, CONST=14, STRING=15, IDENTIFIER=16, 
		VARIABLE=17, FLOAT=18, INT=19, WS=20, COMMENT=21, LINE_COMMENT=22;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "CONST", "STRING", "IDENTIFIER", "VARIABLE", 
		"FLOAT", "INT", "LETTER", "DIGIT", "WS", "COMMENT", "LINE_COMMENT"
	};


	public QikTemplateLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public QikTemplateLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'='", "';'", "'expression'", "'['", "']'", "'{'", "'return'", "'}'", 
		"','", "'+'", "'()'", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, "CONST", "STRING", "IDENTIFIER", "VARIABLE", "FLOAT", "INT", 
		"WS", "COMMENT", "LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "QikTemplate.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static QikTemplateLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x18', '\xC3', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x5', '\xF', 'l', '\n', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\a', '\x10', 'r', '\n', '\x10', 
		'\f', '\x10', '\xE', '\x10', 'u', '\v', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\a', '\x11', '|', 
		'\n', '\x11', '\f', '\x11', '\xE', '\x11', '\x7F', '\v', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', '\x85', 
		'\n', '\x12', '\f', '\x12', '\xE', '\x12', '\x88', '\v', '\x12', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', '\x8D', '\n', '\x13', 
		'\f', '\x13', '\xE', '\x13', '\x90', '\v', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x5', '\x13', '\x94', '\n', '\x13', '\x3', '\x14', '\x6', '\x14', 
		'\x97', '\n', '\x14', '\r', '\x14', '\xE', '\x14', '\x98', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x6', '\x17', 
		'\xA0', '\n', '\x17', '\r', '\x17', '\xE', '\x17', '\xA1', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', 
		'\a', '\x18', '\xAA', '\n', '\x18', '\f', '\x18', '\xE', '\x18', '\xAD', 
		'\v', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\a', '\x19', '\xB8', '\n', '\x19', '\f', '\x19', '\xE', '\x19', '\xBB', 
		'\v', '\x19', '\x3', '\x19', '\x5', '\x19', '\xBE', '\n', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\xAB', '\x2', 
		'\x1A', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', 
		'\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', 
		'\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', 
		'\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x2', '+', '\x2', 
		'-', '\x16', '/', '\x17', '\x31', '\x18', '\x3', '\x2', '\a', '\x3', '\x2', 
		'$', '$', '\x6', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x101', 
		'\x101', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\v', '\f', '\xE', '\xF', 
		'\"', '\"', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x2', '\xCF', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x3', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x5', '\x35', '\x3', '\x2', '\x2', '\x2', '\a', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\t', '\x42', '\x3', '\x2', '\x2', '\x2', '\v', '\x44', 
		'\x3', '\x2', '\x2', '\x2', '\r', '\x46', '\x3', '\x2', '\x2', '\x2', 
		'\xF', 'H', '\x3', '\x2', '\x2', '\x2', '\x11', 'O', '\x3', '\x2', '\x2', 
		'\x2', '\x13', 'Q', '\x3', '\x2', '\x2', '\x2', '\x15', 'S', '\x3', '\x2', 
		'\x2', '\x2', '\x17', 'U', '\x3', '\x2', '\x2', '\x2', '\x19', 'X', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', 'Z', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'k', '\x3', '\x2', '\x2', '\x2', '\x1F', 'm', '\x3', '\x2', '\x2', '\x2', 
		'!', 'x', '\x3', '\x2', '\x2', '\x2', '#', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '%', '\x93', '\x3', '\x2', '\x2', '\x2', '\'', '\x96', '\x3', '\x2', 
		'\x2', '\x2', ')', '\x9A', '\x3', '\x2', '\x2', '\x2', '+', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '-', '\x9F', '\x3', '\x2', '\x2', '\x2', '/', '\xA5', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\xB3', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\x34', '\a', '?', '\x2', '\x2', '\x34', '\x4', '\x3', '\x2', 
		'\x2', '\x2', '\x35', '\x36', '\a', '=', '\x2', '\x2', '\x36', '\x6', 
		'\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\a', 'g', '\x2', '\x2', '\x38', 
		'\x39', '\a', 'z', '\x2', '\x2', '\x39', ':', '\a', 'r', '\x2', '\x2', 
		':', ';', '\a', 't', '\x2', '\x2', ';', '<', '\a', 'g', '\x2', '\x2', 
		'<', '=', '\a', 'u', '\x2', '\x2', '=', '>', '\a', 'u', '\x2', '\x2', 
		'>', '?', '\a', 'k', '\x2', '\x2', '?', '@', '\a', 'q', '\x2', '\x2', 
		'@', '\x41', '\a', 'p', '\x2', '\x2', '\x41', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x42', '\x43', '\a', ']', '\x2', '\x2', '\x43', '\n', '\x3', '\x2', 
		'\x2', '\x2', '\x44', '\x45', '\a', '_', '\x2', '\x2', '\x45', '\f', '\x3', 
		'\x2', '\x2', '\x2', '\x46', 'G', '\a', '}', '\x2', '\x2', 'G', '\xE', 
		'\x3', '\x2', '\x2', '\x2', 'H', 'I', '\a', 't', '\x2', '\x2', 'I', 'J', 
		'\a', 'g', '\x2', '\x2', 'J', 'K', '\a', 'v', '\x2', '\x2', 'K', 'L', 
		'\a', 'w', '\x2', '\x2', 'L', 'M', '\a', 't', '\x2', '\x2', 'M', 'N', 
		'\a', 'p', '\x2', '\x2', 'N', '\x10', '\x3', '\x2', '\x2', '\x2', 'O', 
		'P', '\a', '\x7F', '\x2', '\x2', 'P', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'R', '\a', '.', '\x2', '\x2', 'R', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'S', 'T', '\a', '-', '\x2', '\x2', 'T', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'U', 'V', '\a', '*', '\x2', '\x2', 'V', 'W', '\a', '+', '\x2', '\x2', 
		'W', '\x18', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\a', '*', '\x2', '\x2', 
		'Y', '\x1A', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', '+', '\x2', '\x2', 
		'[', '\x1C', '\x3', '\x2', '\x2', '\x2', '\\', ']', '\a', 'V', '\x2', 
		'\x2', ']', '^', '\a', '\x43', '\x2', '\x2', '^', 'l', '\a', '\x44', '\x2', 
		'\x2', '_', '`', '\a', 'U', '\x2', '\x2', '`', '\x61', '\a', 'R', '\x2', 
		'\x2', '\x61', '\x62', '\a', '\x43', '\x2', '\x2', '\x62', '\x63', '\a', 
		'\x45', '\x2', '\x2', '\x63', 'l', '\a', 'G', '\x2', '\x2', '\x64', '\x65', 
		'\a', 'P', '\x2', '\x2', '\x65', '\x66', '\a', 'G', '\x2', '\x2', '\x66', 
		'g', '\a', 'Y', '\x2', '\x2', 'g', 'h', '\a', 'N', '\x2', '\x2', 'h', 
		'i', '\a', 'K', '\x2', '\x2', 'i', 'j', '\a', 'P', '\x2', '\x2', 'j', 
		'l', '\a', 'G', '\x2', '\x2', 'k', '\\', '\x3', '\x2', '\x2', '\x2', 'k', 
		'_', '\x3', '\x2', '\x2', '\x2', 'k', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'l', '\x1E', '\x3', '\x2', '\x2', '\x2', 'm', 's', '\a', '$', '\x2', '\x2', 
		'n', 'o', '\a', '$', '\x2', '\x2', 'o', 'r', '\a', '$', '\x2', '\x2', 
		'p', 'r', '\n', '\x2', '\x2', '\x2', 'q', 'n', '\x3', '\x2', '\x2', '\x2', 
		'q', 'p', '\x3', '\x2', '\x2', '\x2', 'r', 'u', '\x3', '\x2', '\x2', '\x2', 
		's', 'q', '\x3', '\x2', '\x2', '\x2', 's', 't', '\x3', '\x2', '\x2', '\x2', 
		't', 'v', '\x3', '\x2', '\x2', '\x2', 'u', 's', '\x3', '\x2', '\x2', '\x2', 
		'v', 'w', '\a', '$', '\x2', '\x2', 'w', ' ', '\x3', '\x2', '\x2', '\x2', 
		'x', '}', '\x5', ')', '\x15', '\x2', 'y', '|', '\x5', ')', '\x15', '\x2', 
		'z', '|', '\x5', '+', '\x16', '\x2', '{', 'y', '\x3', '\x2', '\x2', '\x2', 
		'{', 'z', '\x3', '\x2', '\x2', '\x2', '|', '\x7F', '\x3', '\x2', '\x2', 
		'\x2', '}', '{', '\x3', '\x2', '\x2', '\x2', '}', '~', '\x3', '\x2', '\x2', 
		'\x2', '~', '\"', '\x3', '\x2', '\x2', '\x2', '\x7F', '}', '\x3', '\x2', 
		'\x2', '\x2', '\x80', '\x81', '\a', '\x42', '\x2', '\x2', '\x81', '\x86', 
		'\x5', ')', '\x15', '\x2', '\x82', '\x85', '\x5', ')', '\x15', '\x2', 
		'\x83', '\x85', '\x5', '+', '\x16', '\x2', '\x84', '\x82', '\x3', '\x2', 
		'\x2', '\x2', '\x84', '\x83', '\x3', '\x2', '\x2', '\x2', '\x85', '\x88', 
		'\x3', '\x2', '\x2', '\x2', '\x86', '\x84', '\x3', '\x2', '\x2', '\x2', 
		'\x86', '\x87', '\x3', '\x2', '\x2', '\x2', '\x87', '$', '\x3', '\x2', 
		'\x2', '\x2', '\x88', '\x86', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', 
		'\x5', '\'', '\x14', '\x2', '\x8A', '\x8E', '\a', '\x30', '\x2', '\x2', 
		'\x8B', '\x8D', '\x5', '+', '\x16', '\x2', '\x8C', '\x8B', '\x3', '\x2', 
		'\x2', '\x2', '\x8D', '\x90', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8C', 
		'\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\x3', '\x2', '\x2', '\x2', 
		'\x8F', '\x94', '\x3', '\x2', '\x2', '\x2', '\x90', '\x8E', '\x3', '\x2', 
		'\x2', '\x2', '\x91', '\x92', '\a', '\x30', '\x2', '\x2', '\x92', '\x94', 
		'\x5', '\'', '\x14', '\x2', '\x93', '\x89', '\x3', '\x2', '\x2', '\x2', 
		'\x93', '\x91', '\x3', '\x2', '\x2', '\x2', '\x94', '&', '\x3', '\x2', 
		'\x2', '\x2', '\x95', '\x97', '\x5', '+', '\x16', '\x2', '\x96', '\x95', 
		'\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\x3', '\x2', '\x2', '\x2', 
		'\x98', '\x96', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\x3', '\x2', 
		'\x2', '\x2', '\x99', '(', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', 
		'\t', '\x3', '\x2', '\x2', '\x9B', '*', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x9D', '\t', '\x4', '\x2', '\x2', '\x9D', ',', '\x3', '\x2', '\x2', '\x2', 
		'\x9E', '\xA0', '\t', '\x5', '\x2', '\x2', '\x9F', '\x9E', '\x3', '\x2', 
		'\x2', '\x2', '\xA0', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', 
		'\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', 
		'\xA2', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\b', '\x17', 
		'\x2', '\x2', '\xA4', '.', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', 
		'\a', '\x31', '\x2', '\x2', '\xA6', '\xA7', '\a', ',', '\x2', '\x2', '\xA7', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xAA', '\v', '\x2', '\x2', 
		'\x2', '\xA9', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAD', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\xA9', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAE', '\x3', '\x2', '\x2', 
		'\x2', '\xAD', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\a', 
		',', '\x2', '\x2', '\xAF', '\xB0', '\a', '\x31', '\x2', '\x2', '\xB0', 
		'\xB1', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', '\b', '\x18', '\x2', 
		'\x2', '\xB2', '\x30', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB4', '\a', 
		'\x31', '\x2', '\x2', '\xB4', '\xB5', '\a', '\x31', '\x2', '\x2', '\xB5', 
		'\xB9', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB8', '\n', '\x6', '\x2', 
		'\x2', '\xB7', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xBB', '\x3', 
		'\x2', '\x2', '\x2', '\xB9', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xBA', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBD', '\x3', '\x2', '\x2', 
		'\x2', '\xBB', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBE', '\a', 
		'\xF', '\x2', '\x2', '\xBD', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBD', 
		'\xBE', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\x3', '\x2', '\x2', 
		'\x2', '\xBF', '\xC0', '\a', '\f', '\x2', '\x2', '\xC0', '\xC1', '\x3', 
		'\x2', '\x2', '\x2', '\xC1', '\xC2', '\b', '\x19', '\x2', '\x2', '\xC2', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\x11', '\x2', 'k', 'q', 's', '{', 
		'}', '\x84', '\x86', '\x8E', '\x93', '\x98', '\xA1', '\xAB', '\xB9', '\xBD', 
		'\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace CygSoft.Qik.Antlr
