//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Code\you\Qik\Code\Current\QikAntlr\QikTemplate.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CygSoft.Qik.Antlr {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class QikTemplateLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, CONST=15, STRING=16, 
		IDENTIFIER=17, VARIABLE=18, FLOAT=19, INT=20, WS=21, COMMENT=22, LINE_COMMENT=23;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "CONST", "STRING", "IDENTIFIER", 
		"VARIABLE", "FLOAT", "INT", "LETTER", "DIGIT", "WS", "COMMENT", "LINE_COMMENT"
	};


	public QikTemplateLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public QikTemplateLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'='", "';'", "'text'", "'['", "']'", "'expression'", "'{'", "'return'", 
		"'}'", "','", "'+'", "'()'", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, "CONST", "STRING", "IDENTIFIER", "VARIABLE", "FLOAT", 
		"INT", "WS", "COMMENT", "LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "QikTemplate.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static QikTemplateLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x19', '\xCA', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x5', '\x10', 's', '\n', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\a', '\x11', 
		'y', '\n', '\x11', '\f', '\x11', '\xE', '\x11', '|', '\v', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\a', 
		'\x12', '\x83', '\n', '\x12', '\f', '\x12', '\xE', '\x12', '\x86', '\v', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\a', 
		'\x13', '\x8C', '\n', '\x13', '\f', '\x13', '\xE', '\x13', '\x8F', '\v', 
		'\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\a', '\x14', '\x94', 
		'\n', '\x14', '\f', '\x14', '\xE', '\x14', '\x97', '\v', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x5', '\x14', '\x9B', '\n', '\x14', '\x3', '\x15', 
		'\x6', '\x15', '\x9E', '\n', '\x15', '\r', '\x15', '\xE', '\x15', '\x9F', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', 
		'\x6', '\x18', '\xA7', '\n', '\x18', '\r', '\x18', '\xE', '\x18', '\xA8', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\a', '\x19', '\xB1', '\n', '\x19', '\f', '\x19', '\xE', 
		'\x19', '\xB4', '\v', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\a', '\x1A', '\xBF', '\n', '\x1A', '\f', '\x1A', '\xE', 
		'\x1A', '\xC2', '\v', '\x1A', '\x3', '\x1A', '\x5', '\x1A', '\xC5', '\n', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\xB2', '\x2', '\x1B', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', 
		'\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', 
		'\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', 
		'\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', 
		'\x16', '+', '\x2', '-', '\x2', '/', '\x17', '\x31', '\x18', '\x33', '\x19', 
		'\x3', '\x2', '\a', '\x3', '\x2', '$', '$', '\x6', '\x2', '\x43', '\\', 
		'\x61', '\x61', '\x63', '|', '\x101', '\x101', '\x3', '\x2', '\x32', ';', 
		'\x5', '\x2', '\v', '\f', '\xE', '\xF', '\"', '\"', '\x4', '\x2', '\f', 
		'\f', '\xF', '\xF', '\x2', '\xD6', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x3', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\x5', '\x37', '\x3', '\x2', '\x2', '\x2', '\a', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\t', '>', '\x3', '\x2', '\x2', '\x2', '\v', 
		'@', '\x3', '\x2', '\x2', '\x2', '\r', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\xF', 'M', '\x3', '\x2', '\x2', '\x2', '\x11', 'O', '\x3', '\x2', '\x2', 
		'\x2', '\x13', 'V', '\x3', '\x2', '\x2', '\x2', '\x15', 'X', '\x3', '\x2', 
		'\x2', '\x2', '\x17', 'Z', '\x3', '\x2', '\x2', '\x2', '\x19', '\\', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', '_', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\x61', '\x3', '\x2', '\x2', '\x2', '\x1F', 'r', '\x3', '\x2', '\x2', 
		'\x2', '!', 't', '\x3', '\x2', '\x2', '\x2', '#', '\x7F', '\x3', '\x2', 
		'\x2', '\x2', '%', '\x87', '\x3', '\x2', '\x2', '\x2', '\'', '\x9A', '\x3', 
		'\x2', '\x2', '\x2', ')', '\x9D', '\x3', '\x2', '\x2', '\x2', '+', '\xA1', 
		'\x3', '\x2', '\x2', '\x2', '-', '\xA3', '\x3', '\x2', '\x2', '\x2', '/', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\x31', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\xBA', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', 
		'?', '\x2', '\x2', '\x36', '\x4', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\x38', '\a', '=', '\x2', '\x2', '\x38', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'\x39', ':', '\a', 'v', '\x2', '\x2', ':', ';', '\a', 'g', '\x2', '\x2', 
		';', '<', '\a', 'z', '\x2', '\x2', '<', '=', '\a', 'v', '\x2', '\x2', 
		'=', '\b', '\x3', '\x2', '\x2', '\x2', '>', '?', '\a', ']', '\x2', '\x2', 
		'?', '\n', '\x3', '\x2', '\x2', '\x2', '@', '\x41', '\a', '_', '\x2', 
		'\x2', '\x41', '\f', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\a', 
		'g', '\x2', '\x2', '\x43', '\x44', '\a', 'z', '\x2', '\x2', '\x44', '\x45', 
		'\a', 'r', '\x2', '\x2', '\x45', '\x46', '\a', 't', '\x2', '\x2', '\x46', 
		'G', '\a', 'g', '\x2', '\x2', 'G', 'H', '\a', 'u', '\x2', '\x2', 'H', 
		'I', '\a', 'u', '\x2', '\x2', 'I', 'J', '\a', 'k', '\x2', '\x2', 'J', 
		'K', '\a', 'q', '\x2', '\x2', 'K', 'L', '\a', 'p', '\x2', '\x2', 'L', 
		'\xE', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', '}', '\x2', '\x2', 
		'N', '\x10', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', 't', '\x2', '\x2', 
		'P', 'Q', '\a', 'g', '\x2', '\x2', 'Q', 'R', '\a', 'v', '\x2', '\x2', 
		'R', 'S', '\a', 'w', '\x2', '\x2', 'S', 'T', '\a', 't', '\x2', '\x2', 
		'T', 'U', '\a', 'p', '\x2', '\x2', 'U', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'V', 'W', '\a', '\x7F', '\x2', '\x2', 'W', '\x14', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'Y', '\a', '.', '\x2', '\x2', 'Y', '\x16', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '[', '\a', '-', '\x2', '\x2', '[', '\x18', '\x3', '\x2', '\x2', 
		'\x2', '\\', ']', '\a', '*', '\x2', '\x2', ']', '^', '\a', '+', '\x2', 
		'\x2', '^', '\x1A', '\x3', '\x2', '\x2', '\x2', '_', '`', '\a', '*', '\x2', 
		'\x2', '`', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\a', 
		'+', '\x2', '\x2', '\x62', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'\x64', '\a', 'V', '\x2', '\x2', '\x64', '\x65', '\a', '\x43', '\x2', 
		'\x2', '\x65', 's', '\a', '\x44', '\x2', '\x2', '\x66', 'g', '\a', 'U', 
		'\x2', '\x2', 'g', 'h', '\a', 'R', '\x2', '\x2', 'h', 'i', '\a', '\x43', 
		'\x2', '\x2', 'i', 'j', '\a', '\x45', '\x2', '\x2', 'j', 's', '\a', 'G', 
		'\x2', '\x2', 'k', 'l', '\a', 'P', '\x2', '\x2', 'l', 'm', '\a', 'G', 
		'\x2', '\x2', 'm', 'n', '\a', 'Y', '\x2', '\x2', 'n', 'o', '\a', 'N', 
		'\x2', '\x2', 'o', 'p', '\a', 'K', '\x2', '\x2', 'p', 'q', '\a', 'P', 
		'\x2', '\x2', 'q', 's', '\a', 'G', '\x2', '\x2', 'r', '\x63', '\x3', '\x2', 
		'\x2', '\x2', 'r', '\x66', '\x3', '\x2', '\x2', '\x2', 'r', 'k', '\x3', 
		'\x2', '\x2', '\x2', 's', ' ', '\x3', '\x2', '\x2', '\x2', 't', 'z', '\a', 
		'$', '\x2', '\x2', 'u', 'v', '\a', '$', '\x2', '\x2', 'v', 'y', '\a', 
		'$', '\x2', '\x2', 'w', 'y', '\n', '\x2', '\x2', '\x2', 'x', 'u', '\x3', 
		'\x2', '\x2', '\x2', 'x', 'w', '\x3', '\x2', '\x2', '\x2', 'y', '|', '\x3', 
		'\x2', '\x2', '\x2', 'z', 'x', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\x3', 
		'\x2', '\x2', '\x2', '{', '}', '\x3', '\x2', '\x2', '\x2', '|', 'z', '\x3', 
		'\x2', '\x2', '\x2', '}', '~', '\a', '$', '\x2', '\x2', '~', '\"', '\x3', 
		'\x2', '\x2', '\x2', '\x7F', '\x84', '\x5', '+', '\x16', '\x2', '\x80', 
		'\x83', '\x5', '+', '\x16', '\x2', '\x81', '\x83', '\x5', '-', '\x17', 
		'\x2', '\x82', '\x80', '\x3', '\x2', '\x2', '\x2', '\x82', '\x81', '\x3', 
		'\x2', '\x2', '\x2', '\x83', '\x86', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '$', '\x3', '\x2', '\x2', '\x2', '\x86', '\x84', '\x3', 
		'\x2', '\x2', '\x2', '\x87', '\x88', '\a', '\x42', '\x2', '\x2', '\x88', 
		'\x8D', '\x5', '+', '\x16', '\x2', '\x89', '\x8C', '\x5', '+', '\x16', 
		'\x2', '\x8A', '\x8C', '\x5', '-', '\x17', '\x2', '\x8B', '\x89', '\x3', 
		'\x2', '\x2', '\x2', '\x8B', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8D', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '&', '\x3', 
		'\x2', '\x2', '\x2', '\x8F', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x90', 
		'\x91', '\x5', ')', '\x15', '\x2', '\x91', '\x95', '\a', '\x30', '\x2', 
		'\x2', '\x92', '\x94', '\x5', '-', '\x17', '\x2', '\x93', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x94', '\x97', '\x3', '\x2', '\x2', '\x2', '\x95', 
		'\x93', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '\x96', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x97', '\x95', '\x3', 
		'\x2', '\x2', '\x2', '\x98', '\x99', '\a', '\x30', '\x2', '\x2', '\x99', 
		'\x9B', '\x5', ')', '\x15', '\x2', '\x9A', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9B', '(', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9E', '\x5', '-', '\x17', '\x2', '\x9D', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '*', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\xA2', '\t', '\x3', '\x2', '\x2', '\xA2', ',', '\x3', '\x2', '\x2', '\x2', 
		'\xA3', '\xA4', '\t', '\x4', '\x2', '\x2', '\xA4', '.', '\x3', '\x2', 
		'\x2', '\x2', '\xA5', '\xA7', '\t', '\x5', '\x2', '\x2', '\xA6', '\xA5', 
		'\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\x3', '\x2', '\x2', '\x2', 
		'\xA8', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x3', '\x2', 
		'\x2', '\x2', '\xA9', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', 
		'\b', '\x18', '\x2', '\x2', '\xAB', '\x30', '\x3', '\x2', '\x2', '\x2', 
		'\xAC', '\xAD', '\a', '\x31', '\x2', '\x2', '\xAD', '\xAE', '\a', ',', 
		'\x2', '\x2', '\xAE', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB1', 
		'\v', '\x2', '\x2', '\x2', '\xB0', '\xAF', '\x3', '\x2', '\x2', '\x2', 
		'\xB1', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\x3', '\x2', 
		'\x2', '\x2', '\xB2', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB5', 
		'\x3', '\x2', '\x2', '\x2', '\xB4', '\xB2', '\x3', '\x2', '\x2', '\x2', 
		'\xB5', '\xB6', '\a', ',', '\x2', '\x2', '\xB6', '\xB7', '\a', '\x31', 
		'\x2', '\x2', '\xB7', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', 
		'\b', '\x19', '\x2', '\x2', '\xB9', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\xBA', '\xBB', '\a', '\x31', '\x2', '\x2', '\xBB', '\xBC', '\a', '\x31', 
		'\x2', '\x2', '\xBC', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBF', 
		'\n', '\x6', '\x2', '\x2', '\xBE', '\xBD', '\x3', '\x2', '\x2', '\x2', 
		'\xBF', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xBE', '\x3', '\x2', 
		'\x2', '\x2', '\xC0', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC4', 
		'\x3', '\x2', '\x2', '\x2', '\xC2', '\xC0', '\x3', '\x2', '\x2', '\x2', 
		'\xC3', '\xC5', '\a', '\xF', '\x2', '\x2', '\xC4', '\xC3', '\x3', '\x2', 
		'\x2', '\x2', '\xC4', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC6', 
		'\x3', '\x2', '\x2', '\x2', '\xC6', '\xC7', '\a', '\f', '\x2', '\x2', 
		'\xC7', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC9', '\b', '\x1A', 
		'\x2', '\x2', '\xC9', '\x34', '\x3', '\x2', '\x2', '\x2', '\x11', '\x2', 
		'r', 'x', 'z', '\x82', '\x84', '\x8B', '\x8D', '\x95', '\x9A', '\x9F', 
		'\xA8', '\xB2', '\xC0', '\xC4', '\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace CygSoft.Qik.Antlr
