@startuml "One"

scale 3/3

actor "Client" as client
entity "Interpreter" as interpreter
entity "Symbol Terminal" as terminal
client -> interpreter: Interpret()
interpreter -> interpreter: parse script\ncreate scope table
interpreter -> terminal: new()
client <- terminal

@enduml

